### ISSUE TITLE
thanks for help

### ISSUE THREAD

**Issue by simdream** [ZipCPU/zbasic#6]
I am taking zipCPU as an example to learn how to make Verilator used in my project. 

From testb.cpp, I noticed you are use one extra eval() before posedge clock:

                // Pre-evaluate, to give verilator a chance
		// to settle any combinatorial logic that
		// that may have changed since the last clock
		// evaluation, and then record that in the
		// trace.
		eval();

But if this is a synchronous design, should the eval() following clock wagging updated the comb logic also? To add one more eval() here might also slow down the run time performance?

Many thanks,

**Comment by ZipCPU** [comment]
Does this slow down run time performance?  Yes.

I discuss this problem somewhat in lesson 4 of [my tutorial](https://zipcpu.com/tutorial).

Here's the issue: between calls to `tick()`, the C++ hardware emulators might change input ports.  A classic example of this would be the [serial port simulation line](https://github.com/ZipCPU/zbasic/blob/ae7938789d7bb0a14bce865d9163fb294d44c13f/sim/verilated/main_tb.cpp#L245), or even the [SD Card emulator](https://github.com/ZipCPU/zbasic/blob/ae7938789d7bb0a14bce865d9163fb294d44c13f/sim/verilated/main_tb.cpp#L275-L279).  Verilator needs to be told that these values may have changed outside of its view of the world before adjusting things lest the trace ... not make sense.  As it is, because these values are shown to be adjusted just before the clock tick, you might argue that the trace doesn't make sense anyway, but this is the best I've been able to do in order to keep things consistent between the emulated and the simulated environments.
